apiVersion: homer.rajsingh.info/v1alpha1
kind: Item
metadata:
  labels:
    app.kubernetes.io/name: homer-operator
    app.kubernetes.io/managed-by: kustomize
  name: item-sample
spec:
  # TODO(user): Add fields here
